### PR TITLE
apply chromedriver-autoinstaller patch

### PR DESCRIPTION
**Pull request by progressEdd**
Apply the suggested fix from
https://github.com/Derpitron/Discord-OTP-Forcer/issues/131

### CODE REVIEW

**Comment by Derpitron** [comment]
Have you tested this? I will assume you have.

The chromedriver-autoinstaller package which you talk about seems to be unmaintained for 6+ months. I'm not sure if it's stable enough. Do correct me if it works fine, though

**Comment by progressEdd** [comment]
> Have you tested this? I will assume you have.

yes, it was working on my laptop.

> The chromedriver-autoinstaller package which you talk about seems to be unmaintained for 6+ months. I'm not sure if it's stable enough. Do correct me if it works fine, though

the main advantage of chromedriver-autoinstaller is that it the user doesn't have to manually install chromium. The alternate is to have the user install chromium and if selenium doesn't detect it (pass a path manually).


Another potential long term solution is to have a script auto download install similar to playwright 
https://github.com/microsoft/playwright-python/blob/e71bbeb043ddcd79f06970a475832c920d93d9c1/setup.py#L178
https://github.com/microsoft/playwright-python/blob/e71bbeb043ddcd79f06970a475832c920d93d9c1/setup.py#L123

Is webdriver_manager the same as webdriver-manager? Because it looks like there was a update a couple of weeks ago
https://github.com/SergeyPirogov/webdriver_manager

**Comment by Derpitron** [comment]
Does this apply for Google Chrome too? Or just bare Chromium?

**Comment by Derpitron** [comment]
@progressEdd please update me

**Comment by progressEdd** [comment]
> Does this apply for Google Chrome too? Or just bare Chromium?

I only tested with google chrome, let me check with chromium code

**Pull request merged**
